name: techstore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.15
  flutter_bloc: ^8.1.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  get_it: ^8.0.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_stripe: ^11.3.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/fonts/
